### ISSUE TITLE
Error on linux platform

### ISSUE THREAD

**Issue by KevSlashNull** [MyOutDeskLLC/node-browser-history#15]
I know this dependency isn’t supported on linux. However, it throws an ambiguous exception when being imported in an environment with `process.platform === 'linux'`.

```
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at Object.<anonymous> (/home/kev/development/Kev/gitdock/node_modules/node-browser-history/browsers.js:46:25)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

Maybe it can either fail with a more specific error (if `platform === 'linux'`) or not provide any results on the functions.

**Comment by tance77** [comment]
I've never actually run it on Linux. I don't have a Linux system currently up. If you wanted to make a PR i would gladly accept it.

**Comment by KevSlashNull** [comment]
Sure @tance77! I fixed this bug on Linux and also decided to add support for Firefox and Chrome as it only was a simple further step.

I created #17 to add a `LICENSE` file in accordance with the license defined in `package.json`, and the PR #16 to resolve this bug and add linux support. :smile:
